import {
  College,
  Hostel,
  Canteen,
  MenuItem,
  User,
  Order,
  Notification
} from '@/types';

export const SEED_COLLEGE: College = {
  id: 'col-1',
  name: 'Swami Vivekanand Institute of Engineering & Technology',
  code: 'SVIET',
  campus: 'Main Campus',
  isActive: true,
};

export const SEED_HOSTELS: Hostel[] = [
  {
    id: 'hostel-1',
    collegeId: 'col-1',
    name: 'J-Block Boys Hostel',
    blocks: ['Block A', 'Block B', 'Block C'],
    floors: 4,
    totalRooms: 120,
  },
  {
    id: 'hostel-2',
    collegeId: 'col-1',
    name: 'Girls Hostel I-Block',
    blocks: ['East Wing', 'West Wing'],
    floors: 4,
    totalRooms: 100,
  },
  {
    id: 'hostel-3',
    collegeId: 'col-1',
    name: 'D-Block Boys Hostel',
    blocks: ['North Block', 'South Block'],
    floors: 3,
    totalRooms: 80,
  },
];

export const SEED_CANTEENS: Canteen[] = [
  {
    id: 'canteen-main',
    collegeId: 'col-1',
    name: 'Main Campus Canteen',
    tagline: 'Student favorites, fresh meals, and quick bites',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    openTime: '08:00 AM',
    closeTime: '09:30 PM',
    status: 'OPEN',
    avgPrepTimeMinutes: 12,
    rating: 4.7,
    totalReviews: 428,
    hostelDeliveryEnabled: true,
    deliveryTimings: '11:00 AM - 09:00 PM',
    maxDeliveryDistanceMeters: 800,
    currentQueueCount: 3,
  },
  {
    id: 'canteen-night',
    collegeId: 'col-1',
    name: 'Hostel Night Canteen',
    tagline: 'Late night cravings, rolls, burgers & steaming tea',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    openTime: '05:00 PM',
    closeTime: '02:30 AM',
    status: 'OPEN',
    avgPrepTimeMinutes: 10,
    rating: 4.8,
    totalReviews: 615,
    hostelDeliveryEnabled: true,
    deliveryTimings: '06:00 PM - 02:00 AM',
    maxDeliveryDistanceMeters: 600,
    currentQueueCount: 5,
  },
  {
    id: 'canteen-foodcourt',
    collegeId: 'col-1',
    name: 'Engineering Food Court',
    tagline: 'Multi-cuisine counters, wood-fired pizza & cold brews',
    image: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80',
    openTime: '09:00 AM',
    closeTime: '08:00 PM',
    status: 'BUSY',
    avgPrepTimeMinutes: 18,
    rating: 4.5,
    totalReviews: 320,
    hostelDeliveryEnabled: false,
    deliveryTimings: 'Pickup Only (No Delivery)',
    maxDeliveryDistanceMeters: 0,
    currentQueueCount: 8,
  },
];

export const SEED_MENU_ITEMS: MenuItem[] = [
  // Main Canteen
  {
    id: 'item-1',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Veg Crispy Burger',
    description: 'Crispy herb potato patty, fresh lettuce, tomato slice, and creamy house mayo.',
    price: 70,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 10,
    category: 'FAST_FOOD',
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    calories: 360,
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 'item-2',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Paneer Tikka Kathi Roll',
    description: 'Smoky grilled paneer cubes, tossed bell peppers, mint chutney wrapped in a flaky paratha.',
    price: 90,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 12,
    category: 'SNACKS',
    image: '/images/paneer-butter-roll.jpg',
    rating: 4.8,
    calories: 410,
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 'item-3',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Special Masala Dosa',
    description: 'Crisp golden crepe stuffed with spiced potato masala, served with piping hot sambar and coconut chutney.',
    price: 80,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 12,
    category: 'MEALS',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    calories: 320,
    isPopular: true,
  },
  {
    id: 'item-4',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Chole Bhature Platter',
    description: 'Two fluffy golden bhatures served with rich Amritsari chole, pickled onions, and green chilli.',
    price: 100,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 15,
    category: 'MEALS',
    image: 'https://images.unsplash.com/photo-1788602564560-9bcbf0f9acb6?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    calories: 580,
    isPopular: true,
  },
  {
    id: 'item-5',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Cold Coffee with Choco Drizzle',
    description: 'Thick, creamy chilled espresso blend topped with rich chocolate syrup and choco chips.',
    price: 60,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 5,
    category: 'BEVERAGES',
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    calories: 210,
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 'item-6',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Adrak Masala Cutting Chai',
    description: 'Freshly brewed aromatic tea infused with crushed ginger, cardamom, and whole milk.',
    price: 20,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 4,
    category: 'TEA_COFFEE',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    calories: 80,
    isPopular: true,
  },
  {
    id: 'item-7',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Margherita Farmhouse Pizza',
    description: 'Freshly baked thin crust loaded with 100% mozzarella, sweet basil, capsicum, and roasted corn.',
    price: 150,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 15,
    category: 'PIZZA',
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    calories: 520,
  },
  {
    id: 'item-8',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Crispy Peri-Peri French Fries',
    description: 'Golden potato fries seasoned with zesty African peri-peri spice mix with garlic dip.',
    price: 65,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 7,
    category: 'FAST_FOOD',
    image: 'https://images.unsplash.com/photo-1598679253544-2c97992403ea?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    calories: 280,
  },
  {
    id: 'item-9',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Spicy Schezwan Hakka Noodles',
    description: 'Wok-tossed noodles with shredded cabbage, carrots, spring onions in fiery Schezwan sauce.',
    price: 90,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 10,
    category: 'CHINESE',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    calories: 390,
  },
  {
    id: 'item-10',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    name: 'Chocolate Lava Molten Cake',
    description: 'Warm, gooey chocolate fudge center cake dusted with powdered sugar.',
    price: 75,
    isVeg: true,
    isAvailable: false, // Demo out of stock item
    prepTimeMinutes: 8,
    category: 'DESSERTS',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    calories: 340,
  },

  // Hostel Night Canteen
  {
    id: 'item-11',
    canteenId: 'canteen-night',
    canteenName: 'Hostel Night Canteen',
    name: 'Double Egg Chicken Roll',
    description: 'Two fluffy eggs layered over paratha with spiced succulent chicken chunks and chopped onions.',
    price: 110,
    isVeg: false,
    isAvailable: true,
    prepTimeMinutes: 10,
    category: 'SNACKS',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    calories: 490,
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 'item-12',
    canteenId: 'canteen-night',
    canteenName: 'Hostel Night Canteen',
    name: 'Midnight Maggi with Cheese & Herbs',
    description: 'Classic 2-minute nostalgia bowl loaded with melted cheddar, butter, and oregano.',
    price: 55,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 6,
    category: 'FAST_FOOD',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    calories: 310,
    isPopular: true,
    isFeatured: true,
  },
  {
    id: 'item-13',
    canteenId: 'canteen-night',
    canteenName: 'Hostel Night Canteen',
    name: 'Smoky Crispy Chicken Burger',
    description: 'Crispy fried chicken breast fillet, chipotle sauce, cheddar slice, and crunchy pickles.',
    price: 120,
    isVeg: false,
    isAvailable: true,
    prepTimeMinutes: 12,
    category: 'FAST_FOOD',
    image: 'https://images.unsplash.com/photo-1637710847214-f91d99669e18?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    calories: 480,
    isPopular: true,
  },
  {
    id: 'item-14',
    canteenId: 'canteen-night',
    canteenName: 'Hostel Night Canteen',
    name: 'Hot Bournvita with Marshmallows',
    description: 'Malty chocolate milk served steaming hot in an earthen kulhad.',
    price: 35,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 4,
    category: 'BEVERAGES',
    image: 'https://images.unsplash.com/photo-1637572815755-c4b80092dce1?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    calories: 160,
  },
  {
    id: 'item-15',
    canteenId: 'canteen-night',
    canteenName: 'Hostel Night Canteen',
    name: 'Butter Pav Bhaji (2 Pavs)',
    description: 'Mashed spiced vegetable curry simmered on tawa with generous butter and soft toasted pavs.',
    price: 85,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 8,
    category: 'SNACKS',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    calories: 420,
  },

  // Food Court
  {
    id: 'item-16',
    canteenId: 'canteen-foodcourt',
    canteenName: 'Engineering Food Court',
    name: 'Chilli Paneer Gravy with Fried Rice',
    description: 'Indo-Chinese wok bowl with crispy paneer cubes in tangy soy-garlic sauce over jasmine rice.',
    price: 135,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 15,
    category: 'CHINESE',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
    calories: 520,
  },
  {
    id: 'item-17',
    canteenId: 'canteen-foodcourt',
    canteenName: 'Engineering Food Court',
    name: 'BBQ Chicken Feast Pizza (Medium)',
    description: 'Barbecue glazed roasted chicken, red onions, smoked mozzarella, and fresh coriander.',
    price: 199,
    isVeg: false,
    isAvailable: true,
    prepTimeMinutes: 18,
    category: 'PIZZA',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    calories: 640,
    isPopular: true,
  },
  {
    id: 'item-18',
    canteenId: 'canteen-foodcourt',
    canteenName: 'Engineering Food Court',
    name: 'Paneer Butter Masala Thali',
    description: 'Rich paneer gravy, yellow dal tadka, jeera rice, 2 butter rotis, papad, and gulab jamun.',
    price: 160,
    isVeg: true,
    isAvailable: true,
    prepTimeMinutes: 16,
    category: 'MEALS',
    image: 'https://images.unsplash.com/photo-1742281257687-092746ad6021?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    calories: 690,
  },
];

export const SEED_USERS: User[] = [
  {
    id: 'user-student-hosteller',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@college.edu',
    phone: '+91 98765 43210',
    role: 'STUDENT',
    collegeId: 'col-1',
    collegeName: 'Swami Vivekanand Institute of Engineering & Technology',
    studentId: '22BCSE104',
    studentType: 'HOSTELLER',
    hostelDetails: {
      hostelId: 'hostel-1',
      hostelName: 'J-Block Boys Hostel',
      block: 'Block B',
      floor: '2nd Floor',
      roomNumber: '204',
    },
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'user-student-dayscholar',
    name: 'Priya Patel',
    email: 'priya.patel@college.edu',
    phone: '+91 98765 12345',
    role: 'STUDENT',
    collegeId: 'col-1',
    collegeName: 'Swami Vivekanand Institute of Engineering & Technology',
    studentId: '22BEC042',
    studentType: 'DAY_SCHOLAR',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-09-02T11:00:00Z',
  },
  {
    id: 'user-canteen-staff',
    name: 'Ramesh Kumar',
    email: 'ramesh.canteen@college.edu',
    phone: '+91 98111 22334',
    role: 'CANTEEN_STAFF',
    collegeId: 'col-1',
    collegeName: 'Swami Vivekanand Institute of Engineering & Technology',
    canteenId: 'canteen-main',
    canteenName: 'Main Campus Canteen',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'user-delivery-staff',
    name: 'Suresh Yadav',
    email: 'suresh.delivery@college.edu',
    phone: '+91 98222 33445',
    role: 'DELIVERY_STAFF',
    collegeId: 'col-1',
    collegeName: 'Swami Vivekanand Institute of Engineering & Technology',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-08-20T09:00:00Z',
  },
  {
    id: 'user-admin',
    name: 'Yash Vardhan',
    email: 'admin.canteen@college.edu',
    phone: '+91 98000 11223',
    role: 'ADMIN',
    collegeId: 'col-1',
    collegeName: 'Swami Vivekanand Institute of Engineering & Technology',
    isVerified: true,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    createdAt: '2026-08-01T08:00:00Z',
  },
];

export const SEED_INITIAL_ORDERS: Order[] = [];

export const SEED_INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-student-hosteller',
    role: 'STUDENT',
    orderId: 'CB-20260929-00101',
    title: 'Order Preparing 🍳',
    message: 'Main Campus Canteen has started preparing your order CB-20260929-00101. Estimated 8 mins remaining.',
    type: 'ORDER',
    isRead: false,
    createdAt: new Date(Date.now() - 4 * 60000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-student-hosteller',
    role: 'STUDENT',
    orderId: 'CB-20260929-00102',
    title: 'Order Ready & Delivery Assigned 🚀',
    message: 'Your hostel room delivery has been accepted! Suresh Yadav has been assigned for room delivery.',
    type: 'DELIVERY',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-canteen-staff',
    role: 'CANTEEN_STAFF',
    orderId: 'CB-20260929-00103',
    title: 'New Order Received 🔔',
    message: 'Priya Patel placed order CB-20260929-00103 (₹85). Tap to accept or reject.',
    type: 'ORDER',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60000).toISOString(),
  },
];
